
		<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes, minimum-scale=1.0">
		<link rel="stylesheet" type="text/css" href="./styles.css">
		<link rel="stylesheet" type="text/css" href="./prism.css">
		<script src="./prism.js"></script>
		</head><body><div class="page__inner"><main class="main main_width-limit"><article itemscope="" itemtype="http://schema.org/TechArticle"><meta content="Свои ошибки, наследование от Error" itemprop="name"><div itemprop="author" itemscope="" itemtype="http://schema.org/Person"><meta content="iliakan@gmail.com" itemprop="email"><meta content="Ilya Kantor" itemprop="name"/></meta></div><div itemprop="articleBody"><p>Когда мы работаем с внешними данными, возможны самые разные ошибки.</p>
<p>Если приложение сложное, то ошибки естественным образом укладываются в иерархию, разобраться в которой помогает <code>instanceof</code>.</p>
<h2><a class="main__anchor" href="#свой-объект-ошибки" name="свой-объект-ошибки">Свой объект ошибки</a></h2><p>Для примера создадим функцию <code>readUser(json)</code>, которая будет разбирать JSON с данными посетителя. Мы его получаем с сервера – может, нашего, а может – чужого, в общем – желательно проверить на ошибки. А может, это даже и не JSON, а какие-то другие данные – не важно, для наглядности поработаем с JSON.</p>
<p>Пример <code>json</code> на входе в функцию: <code>{ "name": "Вася", "age": 30 }</code>.</p>
<p>В процессе работы <code>readUser</code> возможны различные ошибки. Одна – очевидно, <code>SyntaxError</code> – если передан некорректный JSON.</p>
<p>Но могут быть и другие, например <code>PropertyError</code> – эта ошибка будет возникать, если в прочитанном объекте нет свойства <code>name</code> или <code>age</code>.</p>
<p>Реализуем класс <code>PropertyError</code>:</p>
<div class="code-example" data-trusted="1">
<div class="codebox code-example__codebox">
<div class="codebox__code" data-code="1">
<pre class="line-numbers language-javascript"><code class="language-javascript">function PropertyError(property) {
  Error.call(this, property) ;
  this.name = "PropertyError";

  this.property = property;
  this.message = "Ошибка в свойстве " + property;

  if (Error.captureStackTrace) {
    Error.captureStackTrace(this, PropertyError);
  } else {
    this.stack = (new Error()).stack;
  }

}

PropertyError.prototype = Object.create(Error.prototype);</code></pre>
</div>
</div>
</div><p>В этом коде вы можете видеть ряд важных деталей, важных именно для ошибок:</p>
<dl>
<dt><code>name</code> – имя ошибки.</dt>
<dd>
<p>Должно совпадать с именем функции.</p>
</dd>
<dt><code>message</code> – сообщение об ошибке.</dt>
<dd>
<p>Несмотря на то, что <code>PropertyError</code> наследует от <code>Error</code> (последняя строка), конструктор у неё немного другой. Он принимает не сообщение об ошибке, а название свойства <code>property</code>, ну а сообщение генерируется из него.</p>
<p>В результате в объекте ошибки есть как стандартное свойство <code>message</code>, так и более точное <code>property</code>.</p>
<p>Это частая практика – добавлять в объект ошибки свойства, которых нет в базовых объектах <code>Error</code>, более подробно описывающие ситуацию для данного класса ошибок.</p>
</dd>
<dt><code>stack</code> – стек вызовов, которые в итоге привели к ошибке.</dt>
<dd>
<p>У встроенных объектов <code>Error</code> это свойство есть автоматически, вот к примеру:</p>
<div class="code-example" data-trusted="1">
<div class="codebox code-example__codebox">
<div class="toolbar codebox__toolbar">
<div class="toolbar__tool">
<a class="toolbar__button toolbar__button_run" data-action="run" href="#" title="выполнить"></a>
</div>
<div class="toolbar__tool">
<a class="toolbar__button toolbar__button_edit" data-action="edit" href="#" target="_blank" title="открыть в песочнице"></a>
</div>
</div>
<div class="codebox__code" data-code="1">
<pre class="line-numbers language-javascript"><code class="language-javascript">function f() {
  alert( new Error().stack );
}

f(); // выведет список вложенных вызовов, с номерами строк, где они были сделаны</code></pre>
</div>
</div>
</div><p>Если же объект ошибки делаем мы, то «по умолчанию» такого свойства у него не будет. Нам нужно как-то самим узнавать последовательность вложенных вызовов на текущий момент. Однако удобного способа сделать это в JavaScript нет, поэтому мы поступаем хитро и копируем его из нового объекта <code>new Error</code>, который генерируем тут же.</p>
<p>В V8 (Chrome, Opera, Node.JS) есть нестандартное расширение <a href="https://code.google.com/p/v8-wiki/wiki/JavaScriptStackTraceApi">Error.captureStackTrace</a>, которое позволяет получить стек.</p>
<p>Это делает строка из кода выше:</p>
<div class="code-example" data-trusted="1">
<div class="codebox code-example__codebox">
<div class="codebox__code" data-code="1">
<pre class="line-numbers language-javascript"><code class="language-javascript">Error.captureStackTrace(this, PropertyError);</code></pre>
</div>
</div>
</div><p>Такой вызов записывает в объект <code>this</code> (текущий объект ошибки) стек вызовов, ну а второй аргумент – вообще не обязателен, но если есть, то говорит, что при генерации стека нужно на этой функции остановиться. В результате в стеке будет информация о цепочке вложенных вызовов вплоть до вызова <code>PropertyError</code>.</p>
<p>То есть, будет последовательность вызовов до генерации ошибки, но не включая код самого конструктора ошибки, который, как правило, не интересен. Такое поведение максимально соответствует встроенным ошибкам JavaScript.</p>
</dd>
</dl>
<div class="important important_smart">
<div class="important__header"><span class="important__type">Конструктор родителя здесь не обязателен</span></div>
<div class="important__content"><p>Обычно, когда мы наследуем, то вызываем конструктор родителя. В данном случае вызов выглядит как <code>Error.call(this, message)</code>.</p>
<p>Строго говоря, этот вызов здесь не обязателен. Встроенный конструктор <code>Error</code> ничего полезного не делает, даже свойство <code>this.message</code> (не говоря уже об <code>name</code> и <code>stack</code>) не назначает. Единственный возможный смысл его вызова – он ставит специальное внутреннее свойство <code>[[ErrorData]]</code>, которое выводится в <code>toString</code> и позволяет увидеть, что это ошибка. Поэтому по стандарту вызывать конструктор <code>Error</code> при наследовании в таких случаях рекомендовано.</p>
</div></div>
<h2><a class="main__anchor" href="#instanceof-try-catch" name="instanceof-try-catch">instanceof + try…catch = ♡</a></h2><p>Давайте теперь используем наш новый класс для <code>readUser</code>:</p>
<div class="code-example" data-highlight-block="0-0,17-17,33-33,41-41" data-trusted="1">
<div class="codebox code-example__codebox">
<div class="toolbar codebox__toolbar">
<div class="toolbar__tool">
<a class="toolbar__button toolbar__button_run" data-action="run" href="#" title="выполнить"></a>
</div>
<div class="toolbar__tool">
<a class="toolbar__button toolbar__button_edit" data-action="edit" href="#" target="_blank" title="открыть в песочнице"></a>
</div>
</div>
<div class="codebox__code" data-code="1">
<pre class="line-numbers language-javascript"><code class="language-javascript">// Объявление
function PropertyError(property) {
  this.name = "PropertyError";

  this.property = property;
  this.message = "Ошибка в свойстве " + property;

  if (Error.captureStackTrace) {
    Error.captureStackTrace(this, PropertyError);
  } else {
    this.stack = (new Error()).stack;
  }

}

PropertyError.prototype = Object.create(Error.prototype);

// Генерация ошибки
function readUser(data) {

  var user = JSON.parse(data);

  if (!user.age) {
    throw new PropertyError("age");
  }

  if (!user.name) {
    throw new PropertyError("name");
  }

  return user;
}

// Запуск и try..catch

try {
  var user = readUser('{ "age": 25 }');
} catch (err) {
  if (err instanceof PropertyError) {
    if (err.property == 'name') {
      // если в данном месте кода возможны анонимы, то всё нормально
      alert( "Здравствуйте, Аноним!" );
    } else {
      alert( err.message ); // Ошибка в свойстве ...
    }
  } else if (err instanceof SyntaxError) {
    alert( "Ошибка в синтаксисе данных: " + err.message );
  } else {
    throw err; // неизвестная ошибка, не знаю что с ней делать
  }
}</code></pre>
</div>
</div>
</div><p>Всё работает – и наша ошибка <code>PropertyError</code> и встроенная <code>SyntaxError</code> корректно генерируются, перехватываются, обрабатываются.</p>
<p>Обратим внимание на проверку типа ошибки в <code>try..catch</code>. Оператор <code>instanceof</code> проверяет класс с учётом наследования. Это значит, что если мы в дальнейшем решим создать новый тип ошибки, наследующий от  <code>PropertyError</code>, то проверка <code>err instanceof PropertyError</code> для класса-наследника тоже будет работать. Код получился расширяемым, это очень важно.</p>
<h2><a class="main__anchor" href="#дальнейшее-наследование" name="дальнейшее-наследование">Дальнейшее наследование</a></h2><p><code>PropertyError</code> – это просто общего вида ошибка в свойстве. Создадим ошибку <code>PropertyRequiredError</code>, которая означает, что свойства нет.</p>
<p>Это подвид <code>PropertyError</code>, так что унаследуем от неё. Общий вид конструктора-наследника – стандартный:</p>
<div class="code-example" data-trusted="1">
<div class="codebox code-example__codebox">
<div class="codebox__code" data-code="1">
<pre class="line-numbers language-javascript"><code class="language-javascript">function PropertyRequiredError(property) {
  // вызываем конструктор родителя и передаём текущие аргументы
  PropertyError.apply(this, arguments);
  ...
}</code></pre>
</div>
</div>
</div><p>Достаточно ли в наследнике просто вызвать конструктор родителя? Увы, нет.</p>
<p>Если так поступить, то свойство <code>this.name</code> будет некорректным, да и <code>Error.captureStackTrace</code> тоже получит неправильную функцию вторым параметром.</p>
<p>Можно ли как-то поправить конструктор родителя, чтобы от него было проще наследовать?</p>
<p>Для этого нужно убрать из него упоминания о конкретном классе <code>PropertyError</code>, чтобы сделать код универсальным. Частично – это возможно. Как мы помним, существует свойство <code>constructor</code>, которое есть в <code>prototype</code> по умолчанию, и которое мы можем намеренно сохранить при наследовании.</p>
<p>Исправим родителя <code>PropertyError</code> для более удобного наследования от него:</p>
<div class="code-example" data-highlight-block="15-15" data-highlight-inline="7:34-50" data-trusted="1">
<div class="codebox code-example__codebox">
<div class="codebox__code" data-code="1">
<pre class="line-numbers language-javascript"><code class="language-javascript">function PropertyError(property) {
  this.name = "PropertyError";

  this.property = property;
  this.message = "Ошибка в свойстве " + property;

  if (Error.captureStackTrace) {
    Error.captureStackTrace(this, this.constructor); // (*)
  } else {
    this.stack = (new Error()).stack;
  }

}

PropertyError.prototype = Object.create(Error.prototype);
PropertyError.prototype.constructor = PropertyError;</code></pre>
</div>
</div>
</div><p>В строке <code>(*)</code> вместо ссылки на <code>PropertyError</code> используем <code>constructor</code> чтобы получить именно конструктор для текущего объекта. В наследнике там будет <code>PropertyRequiredError</code>, как и задумано.</p>
<p>Мы убрали одну жёсткую привязку к <code>PropertyError</code>, но со второй (<code>this.name</code>), увы, сложности. Оно должно содержать имя ошибки, то есть, имя её функции-конструктора. Его можно получить через <code>this.name = this.constructor.name</code>, но в IE11- это работать не будет.</p>
<p>Если подерживать IE11-, то тут уж придётся в наследнике его записывать вручную.</p>
<p>Полный код для наследника:</p>
<div class="code-example" data-trusted="1">
<div class="codebox code-example__codebox">
<div class="codebox__code" data-code="1">
<pre class="line-numbers language-javascript"><code class="language-javascript">function PropertyRequiredError(property) {
  PropertyError.apply(this, arguments);
  this.name = 'PropertyRequiredError';
  this.message = 'Отсутствует свойство ' + property;
}

PropertyRequiredError.prototype = Object.create(PropertyError.prototype);
PropertyRequiredError.prototype.constructor = PropertyRequiredError;

var err = new PropertyRequiredError("age");
// пройдёт проверку
alert( err instanceof PropertyError ); // true</code></pre>
</div>
</div>
</div><p>Здесь заодно и <code>message</code> в наследнике было перезаписано на более точное. Если хочется избежать записи и перезаписи, то можно оформить его в виде геттера через <code>Object.defineProperty</code>.</p>
<h2><a class="main__anchor" href="#итого" name="итого">Итого</a></h2><ul>
<li>Чтобы наследовать от ошибок <code>Error</code>, нужно самостоятельно позаботиться о <code>name</code>, <code>message</code> и <code>stack</code>.</li>
<li>Благодаря тому, что <code>instanceof</code> поддерживает наследование, удобно организуются проверки на нужный тип. В иерархию ошибок можно в любой момент добавить новые классы, с понятным кодом и предсказуемым поведением.</li>
</ul>
<p>Чтобы создавать наследники от <code>Error</code> было проще, можно создать класс <code>CustomError</code>, записать в него универсальный код, наподобие <code>PropertyError</code> и далее наследовать уже от него:</p>
<div class="code-example" data-highlight-block="0-0,16-16,27-27,37-37" data-trusted="1">
<div class="codebox code-example__codebox">
<div class="codebox__code" data-code="1">
<pre class="line-numbers language-javascript"><code class="language-javascript">// общего вида "наша" ошибка
function CustomError(message) {
  this.name = "CustomError";
  this.message = message;

  if (Error.captureStackTrace) {
    Error.captureStackTrace(this, this.constructor);
  } else {
    this.stack = (new Error()).stack;
  }

}

CustomError.prototype = Object.create(Error.prototype);
CustomError.prototype.constructor = CustomError;

// наследник
function PropertyError(property) {
  CustomError.call(this, "Отсутствует свойство " + property)
  this.name = "PropertyError";

  this.property = property;
}

PropertyError.prototype = Object.create(CustomError.prototype);
PropertyError.prototype.constructor = PropertyError;

// и ещё уровень
function PropertyRequiredError(property) {
  PropertyError.call(this, property);
  this.name = 'PropertyRequiredError';
  this.message = 'Отсутствует свойство ' + property;
}

PropertyRequiredError.prototype = Object.create(PropertyError.prototype);
PropertyRequiredError.prototype.constructor = PropertyRequiredError;

// использование
var err = new PropertyRequiredError("age");
// пройдёт проверку
alert( err instanceof PropertyRequiredError ); // true
alert( err instanceof PropertyError ); // true
alert( err instanceof CustomError ); // true
alert( err instanceof Error ); // true</code></pre>
</div>
</div>
</div></div></meta></article></main></div></body></html>